from pydantic import BaseModel, ConfigDict, Field


class StrictModel(BaseModel):
    """
    Reject fields that are not defined in the model.
    """

    model_config = ConfigDict(extra="forbid")


class Competitor(StrictModel):
    """
    One direct, indirect, or substitute competitor.
    """

    name: str = Field(
        description="Name of the competitor or substitute solution",
    )

    weakness: str = Field(
        description="A weakness or market gap in the competitor",
    )

    advantage: str = Field(
        description=(
            "The proposed startup's advantage over the competitor"
        ),
    )


class SWOTAnalysis(StrictModel):
    """
    SWOT analysis containing exactly three points per category.
    """

    strengths: list[str] = Field(
        min_length=3,
        max_length=3,
        description="Exactly three internal strengths",
    )

    weaknesses: list[str] = Field(
        min_length=3,
        max_length=3,
        description="Exactly three internal weaknesses",
    )

    opportunities: list[str] = Field(
        min_length=3,
        max_length=3,
        description="Exactly three external opportunities",
    )

    threats: list[str] = Field(
        min_length=3,
        max_length=3,
        description="Exactly three external threats",
    )


class AdvisorReport(StrictModel):
    """
    Complete nine-field response generated by FounderOS Advisor.

    Database-generated fields such as id and created_at are not
    included in this Gemini generation schema.
    """

    idea_score: int = Field(
        ge=0,
        le=100,
        description="Overall startup viability score from 0 to 100",
    )

    market_validation: str = Field(
        description=(
            "General and strategic analysis of the target customer, "
            "market demand, validation signals, assumptions, and risks. "
            "Must not invent specific locations, statistics, local laws, "
            "or unverified real-time market information."
        ),
    )

    competitors: list[Competitor] = Field(
        min_length=3,
        max_length=3,
        description=(
            "Exactly three direct, indirect, or substitute competitors"
        ),
    )

    swot: SWOTAnalysis = Field(
        description=(
            "Structured strengths, weaknesses, opportunities, and threats"
        ),
    )

    business_model: str = Field(
        description=(
            "Recommended business model, pricing approach, major costs, "
            "and unit-economics assumptions"
        ),
    )

    revenue_suggestions: list[str] = Field(
        min_length=3,
        max_length=3,
        description=(
            "Exactly three realistic and distinct revenue opportunities"
        ),
    )

    growth_strategy: list[str] = Field(
        min_length=3,
        max_length=3,
        description=(
            "Exactly three general and strategic growth stages covering "
            "days 1-30, days 31-60, and days 61-90. Must not invent "
            "specific locations, statistics, local laws, or unverified "
            "real-time information."
        ),
    )

    legal_considerations: str = Field(
        description=(
            "General categories of business registration, tax, "
            "licensing, privacy and data protection, employment, and "
            "industry compliance relevant to the business. Must not "
            "provide jurisdiction-specific legal advice and must "
            "recommend consulting a qualified local professional."
        ),
    )

    next_steps: list[str] = Field(
        min_length=5,
        max_length=5,
        description=(
            "Exactly five immediate actions in priority order"
        ),
    )