import { useState, useEffect } from "react";
import {
  Sparkles,
  Loader2,
  AlertCircle,
  TrendingUp,
  Target,
  ShieldAlert,
  Users,
  Briefcase,
  DollarSign,
  Rocket,
  Scale,
  CheckCircle2,
  RotateCcw,
  Download,
} from "lucide-react";
import { analyzeStartupIdea, getLatestReport } from "../services/advisor";

export default function Advisor() {
  const [idea, setIdea] = useState("");
  const [loading, setLoading] = useState(false);
  const [downloadingPdf, setDownloadingPdf] = useState(false);
  const [fetchingLatest, setFetchingLatest] = useState(true);
  const [error, setError] = useState(null);
  const [report, setReport] = useState(null);

  useEffect(() => {
    let active = true;
    async function loadLatestReport() {
      try {
        const latest = await getLatestReport();
        if (active && latest) {
          setReport(latest);
          if (latest.idea_description) {
            setIdea(latest.idea_description);
          }
        }
      } catch (err) {
        console.error("Failed to load latest report:", err);
      } finally {
        if (active) {
          setFetchingLatest(false);
        }
      }
    }
    loadLatestReport();
    return () => {
      active = false;
    };
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (idea.trim().length < 10) {
      setError("Please describe your idea in at least 10 characters.");
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const data = await analyzeStartupIdea(idea.trim());
      setReport(data);
    } catch (err) {
      setError(err.message || "Failed to analyze startup idea. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleNewAnalysis = () => {
    setReport(null);
    setIdea("");
    setError(null);
  };

  const handleDownloadPdf = async () => {
    if (!report || !report.id) return;
    setDownloadingPdf(true);
    setError(null);
    try {
      const token = localStorage.getItem("founderos_token");
      const baseUrl = import.meta.env.VITE_API_BASE_URL || "http://localhost:8000";
      const response = await fetch(`${baseUrl}/reports/advisor/${report.id}/pdf`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      if (!response.ok) {
        throw new Error("Failed to download Advisor PDF report.");
      }

      const blob = await response.blob();
      const blobUrl = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = blobUrl;
      link.download = `advisor-report-${report.id}.pdf`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(blobUrl);
    } catch (err) {
      setError(err.message || "Failed to download PDF.");
    } finally {
      setDownloadingPdf(false);
    }
  };

  const getScoreColor = (score) => {
    if (score >= 75) return "text-emerald-600 bg-emerald-50 border-emerald-200";
    if (score >= 50) return "text-amber-600 bg-amber-50 border-amber-200";
    return "text-rose-600 bg-rose-50 border-rose-200";
  };

  if (fetchingLatest) {
    return (
      <div className="max-w-6xl mx-auto py-16 px-4 flex flex-col items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-[var(--gold)] mb-3" />
        <p className="text-sm text-[var(--muted)]">Loading latest analysis report...</p>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto py-6 px-4 space-y-8">
      {/* Header */}
      <header>
        <div className="flex items-center gap-2 mb-1">
          <div className="p-2 rounded-xl bg-[var(--gold-light)]/40 text-[var(--gold-dark)]">
            <Sparkles className="h-6 w-6" />
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight">AI Startup Advisor</h1>
        </div>
        <p className="mt-1 text-sm text-[var(--muted)]">
          Submit your startup idea to receive an instant, 9-point comprehensive analysis generated by Altora.
        </p>
      </header>

      {/* Input Form */}
      <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm">
        <h2 className="text-lg font-semibold mb-2">Describe Your Startup Idea</h2>
        <p className="text-xs text-[var(--muted)] mb-4">
          Provide key details about your target audience, core problem solved, product offering, or revenue model.
        </p>

        <form onSubmit={handleSubmit} className="space-y-4">
          <textarea
            rows={4}
            value={idea}
            onChange={(e) => setIdea(e.target.value)}
            placeholder="e.g. An AI-powered SaaS platform for micro-influencers to automatically manage brand sponsorships, invoices, and contracts in one dashboard..."
            className="w-full rounded-xl border border-[var(--border)] bg-[#FAF7F0]/30 p-4 text-sm focus:border-[var(--gold)] focus:bg-white focus:outline-none focus:ring-1 focus:ring-[var(--gold)] transition-colors resize-none"
            required
            minLength={10}
          />

          <div className="flex items-center justify-between">
            <span className="text-xs text-[var(--muted)]">
              {idea.length} / 5000 characters
            </span>
            <button
              type="submit"
              disabled={loading || idea.trim().length < 10}
              className="flex items-center gap-2 rounded-xl bg-[#1A1A1A] px-6 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-black focus:outline-none focus:ring-2 focus:ring-[var(--gold)] disabled:opacity-50 transition-all cursor-pointer"
            >
              {loading ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  <span>Analyzing Idea...</span>
                </>
              ) : (
                <>
                  <Sparkles className="h-4 w-4 text-[var(--gold)]" />
                  <span>Analyze Idea</span>
                </>
              )}
            </button>
          </div>
        </form>
      </div>

      {/* Error Message */}
      {error && (
        <div className="flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700 animate-fade-in-up">
          <AlertCircle className="h-5 w-5 shrink-0 text-red-500" />
          <span>{error}</span>
        </div>
      )}

      {/* Loading State */}
      {loading && (
        <div className="flex flex-col items-center justify-center py-16 rounded-2xl border border-[var(--border)] bg-white shadow-sm">
          <Loader2 className="h-10 w-10 animate-spin text-[var(--gold)] mb-4" />
          <h3 className="text-base font-semibold text-[var(--text)]">Evaluating Viability & Market Dynamics</h3>
          <p className="text-xs text-[var(--muted)] mt-1">Generating competitor analysis, SWOT breakdown, and strategic growth steps...</p>
        </div>
      )}

      {/* Report View */}
      {report && !loading && (
        <div className="space-y-6 animate-fade-in-up">
          {/* Top Score Banner */}
          <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-6">
            <div>
              <div className="flex items-center justify-between gap-4">
                <span className="text-xs font-semibold uppercase tracking-wider text-[var(--muted)]">Viability Assessment</span>
                <div className="flex items-center gap-2">
                  {report.id && (
                    <button
                      type="button"
                      onClick={handleDownloadPdf}
                      disabled={downloadingPdf}
                      className="flex items-center gap-1.5 px-3 py-1 text-xs font-semibold rounded-lg bg-[#1A1A1A] text-white hover:bg-black transition-colors cursor-pointer disabled:opacity-50"
                    >
                      {downloadingPdf ? (
                        <Loader2 className="h-3.5 w-3.5 animate-spin" />
                      ) : (
                        <Download className="h-3.5 w-3.5 text-[var(--gold)]" />
                      )}
                      <span>Download PDF</span>
                    </button>
                  )}
                  <button
                    type="button"
                    onClick={handleNewAnalysis}
                    className="flex items-center gap-1.5 px-3 py-1 text-xs font-semibold rounded-lg border border-[var(--border)] text-[var(--muted)] hover:text-[var(--text)] hover:bg-neutral-50 transition-colors cursor-pointer"
                  >
                    <RotateCcw className="h-3.5 w-3.5" />
                    <span>New Analysis</span>
                  </button>
                </div>
              </div>
              <h2 className="text-xl font-bold text-[var(--text)] mt-1">Startup Idea Report</h2>
              <p className="text-xs text-[var(--muted)] mt-1">Comprehensive analysis generated based on current market dynamics.</p>
            </div>
            <div className={`flex items-center gap-4 px-6 py-4 rounded-xl border ${getScoreColor(report.idea_score)} shrink-0`}>
              <div className="text-center">
                <span className="block text-3xl font-extrabold">{report.idea_score}</span>
                <span className="text-[10px] font-semibold uppercase tracking-wider">Idea Score / 100</span>
              </div>
            </div>
          </div>

          {/* Grid of Report Sections */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* 1. Market Validation */}
            <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm space-y-3">
              <div className="flex items-center gap-2.5 text-neutral-800 font-semibold border-b border-neutral-100 pb-3">
                <Target className="h-5 w-5 text-blue-600" />
                <h3>Market Validation</h3>
              </div>
              <p className="text-sm text-neutral-700 leading-relaxed whitespace-pre-line">
                {report.market_validation}
              </p>
            </div>

            {/* 2. Business Model */}
            <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm space-y-3">
              <div className="flex items-center gap-2.5 text-neutral-800 font-semibold border-b border-neutral-100 pb-3">
                <Briefcase className="h-5 w-5 text-indigo-600" />
                <h3>Business Model</h3>
              </div>
              <p className="text-sm text-neutral-700 leading-relaxed whitespace-pre-line">
                {report.business_model}
              </p>
            </div>
          </div>

          {/* 3. Competitor Landscape */}
          {report.competitors && report.competitors.length > 0 && (
            <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm space-y-4">
              <div className="flex items-center gap-2.5 text-neutral-800 font-semibold border-b border-neutral-100 pb-3">
                <Users className="h-5 w-5 text-amber-600" />
                <h3>Competitor Analysis</h3>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {report.competitors.map((comp, idx) => (
                  <div key={idx} className="p-4 rounded-xl bg-neutral-50 border border-neutral-200/80 space-y-2">
                    <h4 className="font-bold text-sm text-neutral-900">{comp.name}</h4>
                    <div>
                      <span className="text-[11px] font-semibold text-rose-600 uppercase tracking-wider">Weakness / Gap:</span>
                      <p className="text-xs text-neutral-600 mt-0.5">{comp.weakness}</p>
                    </div>
                    <div>
                      <span className="text-[11px] font-semibold text-emerald-600 uppercase tracking-wider">Your Advantage:</span>
                      <p className="text-xs text-neutral-600 mt-0.5">{comp.advantage}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* 4. SWOT Analysis */}
          {report.swot && (
            <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm space-y-4">
              <div className="flex items-center gap-2.5 text-neutral-800 font-semibold border-b border-neutral-100 pb-3">
                <ShieldAlert className="h-5 w-5 text-purple-600" />
                <h3>SWOT Analysis</h3>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="p-4 rounded-xl bg-emerald-50/70 border border-emerald-200/70">
                  <h4 className="text-xs font-bold text-emerald-800 uppercase tracking-wider mb-2">Strengths</h4>
                  <ul className="space-y-1.5 text-xs text-emerald-950 list-disc list-inside">
                    {report.swot.strengths?.map((item, i) => (
                      <li key={i}>{item}</li>
                    ))}
                  </ul>
                </div>

                <div className="p-4 rounded-xl bg-amber-50/70 border border-amber-200/70">
                  <h4 className="text-xs font-bold text-amber-800 uppercase tracking-wider mb-2">Weaknesses</h4>
                  <ul className="space-y-1.5 text-xs text-amber-950 list-disc list-inside">
                    {report.swot.weaknesses?.map((item, i) => (
                      <li key={i}>{item}</li>
                    ))}
                  </ul>
                </div>

                <div className="p-4 rounded-xl bg-blue-50/70 border border-blue-200/70">
                  <h4 className="text-xs font-bold text-blue-800 uppercase tracking-wider mb-2">Opportunities</h4>
                  <ul className="space-y-1.5 text-xs text-blue-950 list-disc list-inside">
                    {report.swot.opportunities?.map((item, i) => (
                      <li key={i}>{item}</li>
                    ))}
                  </ul>
                </div>

                <div className="p-4 rounded-xl bg-rose-50/70 border border-rose-200/70">
                  <h4 className="text-xs font-bold text-rose-800 uppercase tracking-wider mb-2">Threats</h4>
                  <ul className="space-y-1.5 text-xs text-rose-950 list-disc list-inside">
                    {report.swot.threats?.map((item, i) => (
                      <li key={i}>{item}</li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          )}

          {/* 5. Revenue & Growth */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {report.revenue_suggestions && (
              <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm space-y-3">
                <div className="flex items-center gap-2.5 text-neutral-800 font-semibold border-b border-neutral-100 pb-3">
                  <DollarSign className="h-5 w-5 text-emerald-600" />
                  <h3>Revenue Opportunities</h3>
                </div>
                <ul className="space-y-2 text-sm text-neutral-700">
                  {report.revenue_suggestions.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <span className="h-5 w-5 rounded-full bg-emerald-100 text-emerald-700 text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">
                        {idx + 1}
                      </span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {report.growth_strategy && (
              <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm space-y-3">
                <div className="flex items-center gap-2.5 text-neutral-800 font-semibold border-b border-neutral-100 pb-3">
                  <Rocket className="h-5 w-5 text-blue-600" />
                  <h3>Growth Strategy</h3>
                </div>
                <div className="space-y-2.5 text-sm text-neutral-700">
                  {report.growth_strategy.map((stage, idx) => (
                    <div key={idx} className="p-3 rounded-xl bg-neutral-50 border border-neutral-200/60">
                      <span className="text-xs font-bold text-neutral-500 uppercase tracking-wider block mb-1">
                        Stage {idx + 1}
                      </span>
                      <p className="text-xs text-neutral-800 leading-relaxed">{stage}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* 6. Legal & Next Steps */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm space-y-3">
              <div className="flex items-center gap-2.5 text-neutral-800 font-semibold border-b border-neutral-100 pb-3">
                <Scale className="h-5 w-5 text-neutral-600" />
                <h3>Legal & Compliance</h3>
              </div>
              <p className="text-sm text-neutral-700 leading-relaxed whitespace-pre-line">
                {report.legal_considerations}
              </p>
            </div>

            {report.next_steps && (
              <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm space-y-3">
                <div className="flex items-center gap-2.5 text-neutral-800 font-semibold border-b border-neutral-100 pb-3">
                  <CheckCircle2 className="h-5 w-5 text-teal-600" />
                  <h3>Actionable Next Steps</h3>
                </div>
                <ol className="space-y-2.5 text-sm text-neutral-700">
                  {report.next_steps.map((step, idx) => (
                    <li key={idx} className="flex items-start gap-2.5">
                      <span className="h-5 w-5 rounded-full bg-teal-100 text-teal-800 text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">
                        {idx + 1}
                      </span>
                      <span className="text-xs text-neutral-800 leading-normal">{step}</span>
                    </li>
                  ))}
                </ol>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}