import { useState } from "react";
import {
  Sparkles,
  Loader2,
  AlertCircle,
  TrendingUp,
  ShieldAlert,
  Users,
  Target,
  DollarSign,
  Compass,
  CheckSquare,
  FileText,
  Printer,
  RefreshCw,
  Zap,
} from "lucide-react";
import { analyzeIdea } from "../services/advisor";

const SAMPLE_IDEAS = [
  "B2B SaaS platform for automated invoice reconciliation and cash flow forecasting using machine learning for micro-enterprises.",
  "On-demand local organic farm marketplace connecting smallholder farmers directly to urban restaurants and cafes with temperature-controlled delivery.",
  "AI-powered copilot for specialized boutique law firms to automate initial contract risk reviews and precedent search.",
];

export default function Advisor() {
  const [ideaInput, setIdeaInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [report, setReport] = useState(null);

  const handleSubmit = async (e) => {
    e?.preventDefault();
    if (!ideaInput.trim() || ideaInput.trim().length < 10) {
      setError("Please describe your business idea in at least 10 characters.");
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const data = await analyzeIdea(ideaInput);
      setReport(data);
    } catch (err) {
      setError(err.message || "Failed to generate Advisor analysis. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handlePresetSelect = (presetText) => {
    setIdeaInput(presetText);
    setError(null);
  };

  const handlePrint = () => {
    window.print();
  };

  const getScoreBadgeColor = (score) => {
    if (score >= 80) return "bg-emerald-100 text-emerald-800 border-emerald-300";
    if (score >= 60) return "bg-amber-100 text-amber-800 border-amber-300";
    return "bg-rose-100 text-rose-800 border-rose-300";
  };

  return (
    <div className="max-w-6xl mx-auto py-4 px-2 sm:px-4 print:p-0 print:max-w-none">
      {/* Header */}
      <header className="flex flex-wrap items-center justify-between gap-4 mb-8 print:hidden">
        <div>
          <div className="flex items-center gap-2">
            <Sparkles className="text-[var(--gold)]" size={26} />
            <h1 className="text-2xl font-bold sm:text-3xl tracking-tight">AI Startup Advisor</h1>
          </div>
          <p className="mt-1 text-sm text-[var(--muted)]">
            Instant 9-point strategic viability, market validation, SWOT analysis, and execution roadmap.
          </p>
        </div>

        {report && (
          <button
            onClick={handlePrint}
            className="flex items-center gap-2 rounded-xl bg-white border border-[var(--border)] px-4 py-2 text-sm font-semibold text-[var(--text)] shadow-xs hover:bg-neutral-50 transition-colors"
          >
            <Printer size={16} className="text-[var(--gold)]" />
            <span>Export PDF</span>
          </button>
        )}
      </header>

      {/* Printable Report Header */}
      <div className="hidden print:block mb-8 border-b border-gray-300 pb-4">
        <h1 className="text-3xl font-bold">FounderOS Strategic Advisor Report</h1>
        <p className="text-sm text-gray-500 mt-1">Generated by Altora AI Advisor</p>
      </div>

      {/* Input Form */}
      <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-xs mb-8 print:hidden">
        <form onSubmit={handleSubmit}>
          <label htmlFor="idea_input" className="block text-sm font-semibold text-[var(--text)] mb-2">
            Describe Your Business or Startup Idea
          </label>
          <textarea
            id="idea_input"
            rows={4}
            value={ideaInput}
            onChange={(e) => {
              setIdeaInput(e.target.value);
              if (error) setError(null);
            }}
            placeholder="Explain what your product does, target customers, business model, or market opportunity..."
            className="block w-full rounded-xl border border-[var(--border)] bg-[#FAF7F0]/40 p-4 text-sm font-normal text-[var(--text)] focus:border-[var(--gold)] focus:bg-white focus:outline-none focus:ring-1 focus:ring-[var(--gold)] transition-colors"
          />

          <div className="mt-3 flex flex-wrap items-center justify-between gap-3 text-xs text-[var(--muted)]">
            <span>Minimum 10 characters ({ideaInput.length} / 5000)</span>

            <div className="flex items-center gap-2">
              <span className="font-semibold text-neutral-400">Presets:</span>
              {SAMPLE_IDEAS.map((preset, idx) => (
                <button
                  key={idx}
                  type="button"
                  onClick={() => handlePresetSelect(preset)}
                  className="rounded-lg bg-[var(--section)] px-2.5 py-1 text-xs text-[var(--text)] hover:bg-[var(--gold-light)] transition-colors"
                >
                  Example {idx + 1}
                </button>
              ))}
            </div>
          </div>

          {error && (
            <div className="mt-4 flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">
              <AlertCircle className="h-5 w-5 shrink-0 text-red-500" />
              <span>{error}</span>
            </div>
          )}

          <div className="mt-5 flex justify-end">
            <button
              type="submit"
              disabled={loading || ideaInput.trim().length < 10}
              className="flex items-center gap-2 rounded-xl bg-[#1A1A1A] px-6 py-3 text-sm font-semibold text-white shadow-sm hover:bg-black focus:outline-none focus:ring-2 focus:ring-[var(--gold)] disabled:opacity-50 transition-all cursor-pointer"
            >
              {loading ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin text-[var(--gold)]" />
                  <span>Analyzing Idea...</span>
                </>
              ) : (
                <>
                  <Zap className="h-4 w-4 text-[var(--gold)]" />
                  <span>{report ? "Re-Analyze Idea" : "Generate Analysis"}</span>
                </>
              )}
            </button>
          </div>
        </form>
      </div>

      {/* Loading Skeleton */}
      {loading && (
        <div className="flex flex-col items-center justify-center py-20 rounded-2xl border border-[var(--border)] bg-white shadow-xs">
          <Loader2 className="h-10 w-10 animate-spin text-[var(--gold)] mb-4" />
          <h3 className="text-lg font-semibold text-[var(--text)]">Synthesizing Advisor Report</h3>
          <p className="text-sm text-[var(--muted)] mt-1 max-w-md text-center">
            Evaluating market demand, unit economics, SWOT positioning, and 90-day execution milestones...
          </p>
        </div>
      )}

      {/* Empty State */}
      {!loading && !report && (
        <div className="text-center py-16 px-4 rounded-2xl border border-dashed border-[var(--border)] bg-white/60">
          <Sparkles className="mx-auto h-12 w-12 text-[var(--gold)]/60 mb-3" />
          <h3 className="text-lg font-semibold text-[var(--text)]">No Analysis Generated Yet</h3>
          <p className="text-sm text-[var(--muted)] max-w-md mx-auto mt-1">
            Enter your business concept in the prompt above and click <strong>Generate Analysis</strong> to get a complete strategic breakdown.
          </p>
        </div>
      )}

      {/* Analysis Report Display */}
      {!loading && report && (
        <div className="space-y-8 animate-fade-in-up">
          {/* Top Score Banner */}
          <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-xs flex flex-wrap items-center justify-between gap-6">
            <div>
              <span className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Overall Strategic Viability</span>
              <h2 className="text-2xl font-bold text-[var(--text)] mt-1">Startup Viability Score</h2>
              <p className="text-xs text-[var(--muted)] mt-1">
                Calculated based on target market depth, competitive advantage, and business model clarity.
              </p>
            </div>

            <div className={`flex flex-col items-center justify-center px-6 py-4 rounded-2xl border-2 ${getScoreBadgeColor(report.idea_score)}`}>
              <span className="text-4xl font-extrabold">{report.idea_score}</span>
              <span className="text-xs font-semibold uppercase tracking-wider mt-0.5">/ 100 Viability</span>
            </div>
          </div>

          {/* 2-Column Section 1: Market Validation & Business Model */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Market Validation */}
            <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-xs flex flex-col">
              <div className="flex items-center gap-2 mb-4 pb-3 border-b border-[var(--border)]">
                <TrendingUp className="text-[var(--gold)]" size={20} />
                <h3 className="text-lg font-semibold text-[var(--text)]">Market Validation & Risk Analysis</h3>
              </div>
              <p className="text-sm text-[var(--text)] leading-relaxed whitespace-pre-line flex-1">
                {report.market_validation}
              </p>
            </div>

            {/* Business Model */}
            <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-xs flex flex-col">
              <div className="flex items-center gap-2 mb-4 pb-3 border-b border-[var(--border)]">
                <DollarSign className="text-[var(--gold)]" size={20} />
                <h3 className="text-lg font-semibold text-[var(--text)]">Business Model & Unit Economics</h3>
              </div>
              <p className="text-sm text-[var(--text)] leading-relaxed whitespace-pre-line flex-1">
                {report.business_model}
              </p>
            </div>
          </div>

          {/* Competitors Grid */}
          <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-xs">
            <div className="flex items-center gap-2 mb-4 pb-3 border-b border-[var(--border)]">
              <Users className="text-[var(--gold)]" size={20} />
              <h3 className="text-lg font-semibold text-[var(--text)]">Competitive Landscape</h3>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {report.competitors?.map((comp, idx) => (
                <div key={idx} className="rounded-xl border border-[var(--border)] bg-[#FAF7F0]/30 p-4">
                  <span className="text-xs font-bold text-[var(--gold-dark)] uppercase tracking-wider">Competitor #{idx + 1}</span>
                  <h4 className="font-semibold text-base text-[var(--text)] mt-1">{comp.name}</h4>

                  <div className="mt-3 space-y-2 text-xs">
                    <div>
                      <span className="font-semibold text-rose-700">Competitor Weakness:</span>
                      <p className="text-[var(--text)] mt-0.5">{comp.weakness}</p>
                    </div>
                    <div>
                      <span className="font-semibold text-emerald-700">Your Advantage:</span>
                      <p className="text-[var(--text)] mt-0.5">{comp.advantage}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* SWOT Matrix */}
          <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-xs">
            <div className="flex items-center gap-2 mb-4 pb-3 border-b border-[var(--border)]">
              <Target className="text-[var(--gold)]" size={20} />
              <h3 className="text-lg font-semibold text-[var(--text)]">SWOT Analysis</h3>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Strengths */}
              <div className="rounded-xl border border-emerald-200 bg-emerald-50/40 p-4">
                <h4 className="font-semibold text-emerald-900 text-sm mb-2 flex items-center gap-1.5">
                  <span className="h-2 w-2 rounded-full bg-emerald-500"></span>
                  Strengths (Internal)
                </h4>
                <ul className="space-y-1.5 text-xs text-emerald-950">
                  {report.swot?.strengths?.map((item, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="font-bold">•</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Weaknesses */}
              <div className="rounded-xl border border-rose-200 bg-rose-50/40 p-4">
                <h4 className="font-semibold text-rose-900 text-sm mb-2 flex items-center gap-1.5">
                  <span className="h-2 w-2 rounded-full bg-rose-500"></span>
                  Weaknesses (Internal)
                </h4>
                <ul className="space-y-1.5 text-xs text-rose-950">
                  {report.swot?.weaknesses?.map((item, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="font-bold">•</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Opportunities */}
              <div className="rounded-xl border border-blue-200 bg-blue-50/40 p-4">
                <h4 className="font-semibold text-blue-900 text-sm mb-2 flex items-center gap-1.5">
                  <span className="h-2 w-2 rounded-full bg-blue-500"></span>
                  Opportunities (External)
                </h4>
                <ul className="space-y-1.5 text-xs text-blue-950">
                  {report.swot?.opportunities?.map((item, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="font-bold">•</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Threats */}
              <div className="rounded-xl border border-amber-200 bg-amber-50/40 p-4">
                <h4 className="font-semibold text-amber-900 text-sm mb-2 flex items-center gap-1.5">
                  <span className="h-2 w-2 rounded-full bg-amber-500"></span>
                  Threats (External)
                </h4>
                <ul className="space-y-1.5 text-xs text-amber-950">
                  {report.swot?.threats?.map((item, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="font-bold">•</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>

          {/* Revenue Suggestions & Legal Considerations */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Revenue Suggestions */}
            <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-xs">
              <div className="flex items-center gap-2 mb-4 pb-3 border-b border-[var(--border)]">
                <DollarSign className="text-[var(--gold)]" size={20} />
                <h3 className="text-lg font-semibold text-[var(--text)]">Revenue Streams</h3>
              </div>
              <ul className="space-y-3">
                {report.revenue_suggestions?.map((sug, i) => (
                  <li key={i} className="flex items-start gap-3 rounded-xl border border-[var(--border)] p-3 text-xs text-[var(--text)] bg-[#FAF7F0]/30">
                    <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[var(--gold)] text-[10px] font-bold text-white">
                      {i + 1}
                    </span>
                    <span className="leading-snug">{sug}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Legal Considerations */}
            <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-xs">
              <div className="flex items-center gap-2 mb-4 pb-3 border-b border-[var(--border)]">
                <ShieldAlert className="text-[var(--gold)]" size={20} />
                <h3 className="text-lg font-semibold text-[var(--text)]">Legal & Regulatory Compliance</h3>
              </div>
              <p className="text-sm text-[var(--text)] leading-relaxed whitespace-pre-line">
                {report.legal_considerations}
              </p>
            </div>
          </div>

          {/* Growth Strategy Timeline (90 Days) */}
          <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-xs">
            <div className="flex items-center gap-2 mb-4 pb-3 border-b border-[var(--border)]">
              <Compass className="text-[var(--gold)]" size={20} />
              <h3 className="text-lg font-semibold text-[var(--text)]">90-Day Execution Roadmap</h3>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {report.growth_strategy?.map((stage, idx) => {
                const labels = ["Days 1 – 30 (Foundation)", "Days 31 – 60 (Validation)", "Days 61 – 90 (Scaling)"];
                return (
                  <div key={idx} className="rounded-xl border border-[var(--border)] p-4 bg-white shadow-2xs">
                    <span className="text-xs font-bold text-[var(--gold-dark)] uppercase tracking-wider">{labels[idx] || `Stage ${idx + 1}`}</span>
                    <p className="text-xs text-[var(--text)] leading-relaxed mt-2">{stage}</p>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Immediate Next Steps Checklist */}
          <div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-xs">
            <div className="flex items-center gap-2 mb-4 pb-3 border-b border-[var(--border)]">
              <CheckSquare className="text-[var(--gold)]" size={20} />
              <h3 className="text-lg font-semibold text-[var(--text)]">Immediate Action Items</h3>
            </div>

            <div className="space-y-2">
              {report.next_steps?.map((step, idx) => (
                <div key={idx} className="flex items-start gap-3 p-3 rounded-xl border border-[var(--border)] bg-[#FAF7F0]/40 text-xs">
                  <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-black text-[10px] font-bold text-white">
                    {idx + 1}
                  </span>
                  <span className="text-[var(--text)] font-medium leading-snug">{step}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}